/* This file was generated by SableCC (http://www.sablecc.org/). */

package fun.analysis;

import fun.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAConstTerm(AConstTerm node);
    void caseAIdentTerm(AIdentTerm node);
    void caseAFnTerm(AFnTerm node);
    void caseAFunTerm(AFunTerm node);
    void caseAAppTerm(AAppTerm node);
    void caseAIfTerm(AIfTerm node);
    void caseALetTerm(ALetTerm node);
    void caseABinopTerm(ABinopTerm node);
    void caseACnumConst(ACnumConst node);
    void caseACtrueConst(ACtrueConst node);
    void caseACfalseConst(ACfalseConst node);
    void caseAPlusOp(APlusOp node);
    void caseATimesOp(ATimesOp node);
    void caseAMinusOp(AMinusOp node);
    void caseAAndOp(AAndOp node);
    void caseAOrOp(AOrOp node);
    void caseALsOp(ALsOp node);
    void caseAGtOp(AGtOp node);

    void caseTWhiteSpace(TWhiteSpace node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTCtrue(TCtrue node);
    void caseTCfalse(TCfalse node);
    void caseTFn(TFn node);
    void caseTFun(TFun node);
    void caseTIf(TIf node);
    void caseTThen(TThen node);
    void caseTElse(TElse node);
    void caseTLet(TLet node);
    void caseTIn(TIn node);
    void caseTImplies(TImplies node);
    void caseTIs(TIs node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTTimes(TTimes node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTLs(TLs node);
    void caseTGt(TGt node);
    void caseTInteger(TInteger node);
    void caseTId(TId node);
    void caseEOF(EOF node);
}
