/* This file was generated by SableCC (http://www.sablecc.org/). */

package fun.node;

import fun.analysis.*;

@SuppressWarnings("nls")
public final class AConstTerm extends PTerm
{
    private PConst _const_;

    public AConstTerm()
    {
        // Constructor
    }

    public AConstTerm(
        @SuppressWarnings("hiding") PConst _const_)
    {
        // Constructor
        setConst(_const_);

    }

    @Override
    public Object clone()
    {
        return new AConstTerm(
            cloneNode(this._const_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstTerm(this);
    }
    @SuppressWarnings("unchecked")

    public <T,S> T apply(Switch<T,S> sw, S helper)
    {
        return ((GAnalysis<T,S>) sw).caseAConstTerm(this,helper);
    }


    public PConst getConst()
    {
        return this._const_;
    }

    public void setConst(PConst node)
    {
        if(this._const_ != null)
        {
            this._const_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._const_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._const_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._const_ == child)
        {
            this._const_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._const_ == oldChild)
        {
            setConst((PConst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
