/* This file was generated by SableCC (http://www.sablecc.org/). */

package fun.node;

import fun.analysis.*;

@SuppressWarnings("nls")
public final class TFn extends Token
{
    public TFn()
    {
        super.setText("fn");
    }

    public TFn(int line, int pos)
    {
        super.setText("fn");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFn(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFn(this);
    }

	@SuppressWarnings("unchecked")
	
    public <T,S> T apply(Switch<T,S> sw, S helper)
    {
        return ((GAnalysis<T,S>) sw).caseTFn(this,helper);
    }
    
    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFn text.");
    }
}
