/* This file was generated by SableCC (http://www.sablecc.org/). */

package fun.node;

import fun.analysis.*;

@SuppressWarnings("nls")
public final class TImplies extends Token
{
    public TImplies()
    {
        super.setText("=>");
    }

    public TImplies(int line, int pos)
    {
        super.setText("=>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TImplies(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImplies(this);
    }

	@SuppressWarnings("unchecked")
	
    public <T,S> T apply(Switch<T,S> sw, S helper)
    {
        return ((GAnalysis<T,S>) sw).caseTImplies(this,helper);
    }
    
    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TImplies text.");
    }
}
