/* This file was generated by SableCC (http://www.sablecc.org/). */

package fun.node;

import fun.analysis.*;

@SuppressWarnings("nls")
public final class TIn extends Token
{
    public TIn()
    {
        super.setText("in");
    }

    public TIn(int line, int pos)
    {
        super.setText("in");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIn(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIn(this);
    }

	@SuppressWarnings("unchecked")
	
    public <T,S> T apply(Switch<T,S> sw, S helper)
    {
        return ((GAnalysis<T,S>) sw).caseTIn(this,helper);
    }
    
    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIn text.");
    }
}
