/* This file was generated by SableCC (http://www.sablecc.org/). */

package fun.node;

import fun.analysis.*;

@SuppressWarnings("nls")
public final class TLet extends Token
{
    public TLet()
    {
        super.setText("let");
    }

    public TLet(int line, int pos)
    {
        super.setText("let");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLet(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLet(this);
    }

	@SuppressWarnings("unchecked")
	
    public <T,S> T apply(Switch<T,S> sw, S helper)
    {
        return ((GAnalysis<T,S>) sw).caseTLet(this,helper);
    }
    
    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLet text.");
    }
}
